### ISSUE TITLE
`Milestone 1` Desenvolvimento do MVP

### ISSUE THREAD

**Issue by OtavioVB** [OtavioVB/Eschody#1]
# Milestone 1: Expansão de Origem

Essa milestone será caracterizada pelo desenvolvimento do `MVP` do website.

**Comment by OtavioVB** [comment]
# Regra de Negócios


## Back-End
- [ ] Criação de um sistema de cadastro e login utilizado `ASP. NET Identity`;
- [ ] Criação de um `CRUD` para `eschody:tarefas` como um To-Do List;
- [ ] Criação de um `CRUD` para `eschody:estudos`;

### Eschody: Tarefas

Deverá conter os seguintes campos:
- Título da Tarefa
- Descrição da Tarefa
- Identificador da Tarefa
- Data de Pedido
- Prazo para Entrega
- Identificador do Usuário

### Eschody: Estudos

#### Matéria
- Identificador
- Nome da matéria
- Área da Ciência
- Identificador do Usuário

#### Conteúdo
- Identificador
- Nome do Conteúdo
- Identificador da Matéria
- Identificador do Usuário
